export const getTransactions = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: 'TXN001',
          customerId: 'C001',
          customer: 'Alice',
          amount: 120,
          product: 'Bluetooth Speaker',
          date: '2025-04-05',
        },
        {
          id: 'TXN002',
          customerId: 'C001',
          customer: 'Alice',
          amount: 120,
          product: 'Speaker',
          date: '2025-04-05',
        },
        {
          id: 'TXN003',
          customerId: 'C002',
          customer: 'Bob',
          amount: 75,
          product: 'Keyboard',
          date: '2025-04-07',
        },
        {
          id: 'TXN004',
          customerId: 'C003',
          customer: 'Charlie',
          amount: 95,
          product: 'Monitor Stand',
          date: '2025-04-15',
        },
        {
          id: 'TXN005',
          customerId: 'C001',
          customer: 'Alice',
          amount: 200,
          product: 'Smartwatch',
          date: '2025-05-03',
        },
        {
          id: 'TXN006',
          customerId: 'C002',
          customer: 'Bob',
          amount: 130,
          product: 'Noise-Cancelling Headphones',
          date: '2025-05-10',
        },
        {
          id: 'TXN007',
          customerId: 'C003',
          customer: 'Charlie',
          amount: 45,
          product: 'Webcam',
          date: '2025-05-18',
        },
        {
          id: 'TXN008',
          customerId: 'C001',
          customer: 'Alice',
          amount: 60,
          product: 'USB Hub',
          date: '2025-06-01',
        },
        {
          id: 'TXN009',
          customerId: 'C002',
          customer: 'Bob',
          amount: 95,
          product: 'Mechanical Mouse',
          date: '2025-06-05',
        },
        {
          id: 'TXN010',
          customerId: 'C003',
          customer: 'Charlie',
          amount: 155,
          product: 'Ergonomic Chair',
          date: '2025-06-20',
        },
        {
          id: 'TXN011',
          customerId: 'C001',
          customer: 'Alice',
          amount: 135,
          product: 'Portable SSD',
          date: '2024-02-10',
        },
        {
          id: 'TXN012',
          customerId: 'C002',
          customer: 'Bob',
          amount: 180,
          product: 'Gaming Monitor',
          date: '2024-03-02',
        },
        {
          id: 'TXN013',
          customerId: 'C003',
          customer: 'Charlie',
          amount: 65,
          product: 'Wireless Mouse',
          date: '2024-03-18',
        },
        {
          id: 'TXN014',
          customerId: 'C001',
          customer: 'Alice',
          amount: 220,
          product: 'Tablet',
          date: '2024-04-25',
        },
        {
          id: 'TXN015',
          customerId: 'C002',
          customer: 'Bob',
          amount: 90,
          product: 'Bluetooth Keyboard',
          date: '2024-05-12',
        },
        {
          id: 'TXN016',
          customerId: 'C003',
          customer: 'Charlie',
          amount: 150,
          product: 'Smartphone',
          date: '2024-06-03',
        },
        {
          id: 'TXN017',
          customerId: 'C001',
          customer: 'Alice',
          amount: 40,
          product: 'Laptop Stand',
          date: '2024-07-09',
        },
        {
          id: 'TXN018',
          customerId: 'C002',
          customer: 'Bob',
          amount: 115,
          product: 'Webcam Pro',
          date: '2024-08-21',
        },
        {
          id: 'TXN019',
          customerId: 'C003',
          customer: 'Charlie',
          amount: 175,
          product: 'Noise-Canceling Earbuds',
          date: '2024-09-14',
        },
        {
          id: 'TXN020',
          customerId: 'C001',
          customer: 'Alice',
          amount: 85,
          product: 'Smart Speaker',
          date: '2024-11-28',
        },
      ]);
    }, 1000);
  });
};
